version: '3.8'

services:
  grabha-api:
    image: sreeh007/grabha-api:latest
    container_name: grabha-api
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /home/sreeh007/grabha-web:/app/web:ro
      - /home/sreeh007/grabha-api-git/logs:/root/grabha/logs
      - /home/sreeh007/grabha-cookies:/app/cookies
    environment:
      - PORT=5000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # - TOKEN_SECRET=your-secret
